### PR TITLE
feat(histogram): create an histogram

### LINKED ISSUE #5: create histogram from array

### PR DESCRIPTION
**Pull request by maasencioh**
closes #5 

what do you think?

### CODE REVIEW

**Comment by targos** [comment]
I don't really like the name. Histogram is how we call the graphical representation.
Is this data binning? https://en.wikipedia.org/wiki/Data_binning
Maybe we can call that ml-array-bin or ml-array-binning?

**Comment by targos** [comment]
or ml-array-distribution...

**Comment by targos** [comment]
anyway, are you sure there is no such module already on npm?

**Comment by targos** [comment]
https://github.com/d3/d3-array#histograms

**Comment by jobo322** [comment]
should be nice to have a way to calculate the threshold when it's not provided, because '1' as default value does not work when the data is between 0 - 1 for example

**Comment by jobo322** [comment]
the threshold could be calculated like (max - min) / (len - 1)

**Comment by kjappelbaum** [comment]
Hi, what's the status of this---did you agree that there shouldn't be a package for this and one should use the d3 one? 

For image analysis I would like to compute the fractal dimension (similar to https://francescoturci.net/2016/03/31/box-counting-in-numpy/) and for this it might be neat to have a lightweight (2D) histogram implementation. 

For the width of the bins, I think we could have a good default value using the [Freedman-Diaconis rule](https://en.wikipedia.org/wiki/Freedman%E2%80%93Diaconis_rule).

**Pull request closed without merging**
