### PR TITLE
Added default arguments transpilation 

### PR DESCRIPTION
**Pull request by glebmachine**
Fix of #8

### CODE REVIEW

**Comment by glebmachine** [comment]
Waiting forward your PR guys, thank you!

**Comment by stropitek** [comment]
I'm ok with that

@targos should we keep the CJS build as well?

**Comment by targos** [comment]
I think we need to keep a cjs build for Node?

**Comment by glebmachine** [comment]
Will fix that, back soon!

**Comment by glebmachine** [comment]
@stropitek Done!

**Comment by glebmachine** [comment]
I will be very appreciated if you accept the request today. I have release date today(
Thank you and excuse me for being annoying
@stropitek

**Comment by stropitek** [comment]
two more things:
- Can you remove and ignore the `yarn.lock` file and update the `package-lock` file?
- Can you change change `lib-esm` to `lib-es6`? It's just to be consistent across our packages!

**Comment by targos** [comment]
I'm working on it

**Comment by targos** [comment]
I pushed a change to
- rename the folder to `lib-es6`
- remove yarn.lock
- use the preset-env instead of a specific plugin to provide more compatibility

**Comment by glebmachine** [comment]
Thank you guys!

**Comment by targos** [comment]
@stropitek can you merge (squash) and release please?

**Comment by stropitek** [comment]
yep!

**Comment by stropitek** [comment]
@glebmachine 

I have published the packages

**Pull request merged**
